// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwJXKCLwBgjAzRFYOwly4mEnH88oE5uIk',
    appId: '1:698772848965:web:01d4727d5aba374ca9fe2c',
    messagingSenderId: '698772848965',
    projectId: 'gourmetgo-29bbf',
    authDomain: 'gourmetgo-29bbf.firebaseapp.com',
    storageBucket: 'gourmetgo-29bbf.firebasestorage.app',
    measurementId: 'G-LY04W251Y8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC75R9ie6COPVHrI96VMI1Qs4Cou-jIUgo',
    appId: '1:698772848965:android:99ed86dfe9dcf733a9fe2c',
    messagingSenderId: '698772848965',
    projectId: 'gourmetgo-29bbf',
    storageBucket: 'gourmetgo-29bbf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7QmXO1FpOGdQXpVFqYBJ7wDWD_BrUNmY',
    appId: '1:698772848965:ios:a8e979d3cfb26f8ca9fe2c',
    messagingSenderId: '698772848965',
    projectId: 'gourmetgo-29bbf',
    storageBucket: 'gourmetgo-29bbf.firebasestorage.app',
    iosClientId: '698772848965-4cputv13hhn64995srveqm1kagglreef.apps.googleusercontent.com',
    iosBundleId: 'com.example.gourmetGo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7QmXO1FpOGdQXpVFqYBJ7wDWD_BrUNmY',
    appId: '1:698772848965:ios:a8e979d3cfb26f8ca9fe2c',
    messagingSenderId: '698772848965',
    projectId: 'gourmetgo-29bbf',
    storageBucket: 'gourmetgo-29bbf.firebasestorage.app',
    iosClientId: '698772848965-4cputv13hhn64995srveqm1kagglreef.apps.googleusercontent.com',
    iosBundleId: 'com.example.gourmetGo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwJXKCLwBgjAzRFYOwly4mEnH88oE5uIk',
    appId: '1:698772848965:web:42d25a7c35e19280a9fe2c',
    messagingSenderId: '698772848965',
    projectId: 'gourmetgo-29bbf',
    authDomain: 'gourmetgo-29bbf.firebaseapp.com',
    storageBucket: 'gourmetgo-29bbf.firebasestorage.app',
    measurementId: 'G-LP1RX8FE85',
  );
}
